services:
    innmind_rest_client.formats.content_type:
        class: Innmind\Rest\Client\Formats
        arguments:
            - []
        factory:
            - '@innmind_rest_client.formats_factory'
            - make

    innmind_rest_client.formats_factory:
        class: Innmind\Rest\ClientBundle\FormatsFactory
        public: false
