imports:
    - { resource: 'formats.yml' }
    - { resource: 'transport.yml' }
    - { resource: 'serializer.yml' }

services:
    innmind_rest_client.definition.types:
        class: Innmind\Rest\Client\Definition\Types
        configurator:
            - '@innmind_rest_client.types_configurator'
            - configure

    innmind_rest_client.types_configurator:
        class: Innmind\Rest\ClientBundle\TypesConfigurator
        public: false

    innmind_rest_client.url_resolver:
        class: Innmind\UrlResolver\UrlResolver
        public: false
