services:
    innmind_rest_client.transport: '@innmind_rest_client.transport.logger'

    innmind_rest_client.transport.guzzle:
        class: Innmind\HttpTransport\GuzzleTransport
        public: false
        arguments:
            - '@innmind_rest_client.guzzle'
            - '@innmind_rest_client.psr7_translator'

    innmind_rest_client.transport.catch_guzzle_bad_response_exception:
        class: Innmind\HttpTransport\CatchGuzzleBadResponseExceptionTransport
        public: false
        arguments:
            - '@innmind_rest_client.transport.guzzle'
            - '@innmind_rest_client.psr7_translator'

    innmind_rest_client.transport.throw_on_client_error:
        class: Innmind\HttpTransport\ThrowOnClientErrorTransport
        public: false
        arguments:
            - '@innmind_rest_client.transport.catch_guzzle_bad_response_exception'

    innmind_rest_client.transport.throw_on_server_error:
        class: Innmind\HttpTransport\ThrowOnServerErrorTransport
        public: false
        arguments:
            - '@innmind_rest_client.transport.throw_on_client_error'

    innmind_rest_client.transport.logger:
        class: Innmind\HttpTransport\LoggerTransport
        public: false
        arguments:
            - '@innmind_rest_client.transport.throw_on_server_error'
            - '@logger'
            - 'debug'

    innmind_rest_client.guzzle:
        class: GuzzleHttp\Client
        public: false

    innmind_rest_client.psr7_translator:
        class: Innmind\Http\Translator\Response\Psr7Translator
        public: false
        arguments:
            - '@innmind_rest_client.psr7_translator.factory'

    innmind_rest_client.psr7_translator.factory:
        class: Innmind\Http\Factory\Header\TryFactory
        public: false
        factory:
            - Innmind\Http\Factory\Header\Factories
            - default
